export const resources = [
  {
    id: '1',
    title: 'Learning Next.js',
    description: 'Like to learn Next.js',
    link: 'https://nextjs.org/',
    createdAt: '2018-01-01',
    img: 'https://nextjs.org/assets/img/logo.svg',
    priority: 3,
    timeToFinish: 120,
    active: true,
  },
  {
    id: '2',
    title: 'Learning new tool',
    description: 'Like to learn tool',
    link: 'https://nextjs.org/',
    createdAt: '2018-01-01',
    img: 'https://nextjs.org/assets/img/logo.svg',
    priority: 1,
    timeToFinish: 240,
    active: false,
  },
  {
    id: '3',
    title: 'Learn Redux',
    description: 'Like to learn Redux',
    link: 'https://nextjs.org/',
    createdAt: '2018-01-01',
    img: 'https://nextjs.org/assets/img/logo.svg',
    priority: 3,
    timeToFinish: 50,
    active: false,
  },
];
